name: bela_blok
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.4+7

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  share_plus: ^9.0.0
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  material_symbols_icons: ^4.2810.1
  hugeicons: ^0.0.10
  shared_preferences: ^2.5.2
  url_launcher: ^6.3.1
  wakelock_plus: ^1.2.10
  riverpod_generator: ^2.6.5
  riverpod_annotation: ^2.6.1
  qr_flutter: ^4.1.0
  mobile_scanner: ^6.0.7
  in_app_review: ^2.0.10
  confetti: ^0.8.0
  vibration: ^3.1.3
  fl_chart: ^0.69.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  
  assets:
    - assets/fonts/
    - assets/images/
    
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Nunito-Black.ttf
          weight: 900
        - asset: assets/fonts/Nunito-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Nunito-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Nunito-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Nunito-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Nunito-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Nunito-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Nunito-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Nunito-BlackItalic.ttf
          weight: 900
          style: italic

flutter_launcher_icons:
  android: "launcher_icon"
  adaptive_icon_background: null
  icon background adaptive_icon_foreground: "assets/icon/icon_new.png"
  ios: true
  image_path: "assets/icon/icon_new.png"
  min_sdk_android: 21
  remove_alpha_ios: true